create table movie (id bigint generated by default as identity, name varchar(255), duration time,  primary key (id));
create table movie_schedule (id bigint generated by default as identity, deleted boolean not null, from_date date, price decimal(19,2), time_slot integer, to_date date, movie_id bigint, movie_theatre_id bigint, primary key (id));
create table movie_theatre (id bigint generated by default as identity, address varchar(255), deleted boolean not null, name varchar(255), seat_count integer, primary key (id));
alter table movie_schedule add constraint FKiphejm916oqwk9fodldpacxch foreign key (movie_id) references movie;
alter table movie_schedule add constraint FKfjkctqlt8g6htix20vo4al4f foreign key (movie_theatre_id) references movie_theatre;
